### ISSUE TITLE
DaoException

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Devotion#1]
```
[14:50:12 ERROR]: Could not pass event BlockMultiPlaceEvent to Devotion v1.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:110) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:156) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: com.programmerdan.minecraft.devotion.dao.DAOException: Event class org.bukkit.event.block.BlockMultiPlaceEvent is not registered.
        at com.programmerdan.minecraft.devotion.dao.flyweight.FlyweightFactory.getId(FlyweightFactory.java:148) ~[?:?]
        at com.programmerdan.minecraft.devotion.dao.flyweight.FlyweightFactory.create(FlyweightFactory.java:93) ~[?:?]
        at com.programmerdan.minecraft.devotion.monitors.PlayerInteractionMonitor.insert(PlayerInteractionMonitor.java:163) ~[?:?]
        at com.programmerdan.minecraft.devotion.monitors.PlayerInteractionMonitor.onBlockPlace(PlayerInteractionMonitor.java:347) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        ... 18 more
```

**Comment by Aleksey-Terzi** [comment]
Bug is reproduced and fixed.
It is happening when player is placing multi block item (such as door or bed).
Plugin will save now one record per placed block (so for door or bed this is 2 records) into the dev_block_place table.
