### ISSUE TITLE
Fishing Exception

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Devotion#2]
```
[12:43:50 ERROR]: Could not pass event PlayerFishEvent to Devotion v1.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.EntityFishingHook.l(EntityFishingHook.java:393) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.ItemFishingRod.a(ItemFishingRod.java:15) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:234) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:371) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:730) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to org.bukkit.entity.Item
        at com.programmerdan.minecraft.devotion.dao.flyweight.fPlayerFish.<init>(fPlayerFish.java:26) ~[?:?]
        at com.programmerdan.minecraft.devotion.dao.flyweight.FlyweightFactory.create(FlyweightFactory.java:123) ~[?:?]
        at com.programmerdan.minecraft.devotion.dao.flyweight.FlyweightFactory.create(FlyweightFactory.java:95) ~[?:?]
        at com.programmerdan.minecraft.devotion.monitors.PlayerInteractionMonitor.insert(PlayerInteractionMonitor.java:163) ~[?:?]
        at com.programmerdan.minecraft.devotion.monitors.PlayerInteractionMonitor.onPlayerFish(PlayerInteractionMonitor.java:251) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
```

**Comment by Aleksey-Terzi** [comment]
Bug is reproduced and fixed.
Problem is happening if player trying to catch some entity (in this stack trace - this is another player).
I've introduced new column dev_player_fish.caught_entity_id (plugin will add column if table already exist).
